## 3.1 넘파이배열
많은 숫자 데이터를 하나의 변수에 넣고 관리 할 때 리스트는 속도가 느리고 메모리를 많이 차지하는 단점이 있다. 배열(array)을 사용하면 적은 메모리로 많은 데이터를 빠르게 처리할 수 있다.  
배열은 리스트와 비슷하지만 다음과 같은 점에서 다르다.   
1. 모든 원소가 같은 자료형이어야 한다. 
2. 원소의 갯수를 바꿀 수 없다.   
파이썬은 자체적으료 배열 자료형을 제공하지 않는다. 따라서 파이썬에서 배열을 사용하기 위한 표준 패키지인 넘파이를 임포트 해야한다.   

넘파이는 수치해석용 파이썬 패키지이다. 다차원의 배열자료구조 클래스인 ```ndarray```클래스를 지원하며 벡터와 행렬을 사용하는 선형대수 계산에 주로 사용된다.   

넘파이의 배열 연산은 C로 구현된 내부 반복문을 사용하기 때문에 파이썬 반복문에 비해 속도가 빠르며 벡터화 연산(vectorized operation)을 이용하여 간단한 코드로도 복잡한 선형 대수 연산을 수행할 수 있다. 또한 배열 인덱싱(array indexing)을 사용한 질의(Query) 기능을 이용하여 간단한 코드로도 복잡한 수식을 계산할 수 있다.


### 3.1.1 넘파이 패키지 임포트

In [1]:
import numpy as np

### 3.1.2 1차원 배열 만들기
넘파이의 ```array```함수에 리스트를 넣으면 ```ndarray```클래스 객체, 즉 배열로 변환해 준다. 

In [2]:
ar = np.array([0,1,2,3,4,5,6,7,8,9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(ar)

numpy.ndarray

만들어진 ndarray 객체의 표현식(representation)을 보면 바깥쪽에 array()란 것이 붙어 있을 뿐 리스트와 동일한 구조처럼 보인다. 그러나 배열 객체와 리스트 객체는 많은 차이가 있다.

우선 리스트 클래스 객체는 각각의 원소가 다른 자료형이 될 수 있다. 그러나 배열 객체 객체는 C언어의 배열처럼 연속적인 메모리 배치를 가지기 때문에 모든 원소가 같은 자료형이어야 한다. 이러한 제약사항이 있는 대신 원소에 대한 접근과 반복문 실행이 빨라진다

### 3.1.3 벡터화 연산
배열 객체는 배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리하는 벡터화 연산(vectorized operation)을 지원한다.

In [7]:
# 2배 만들기
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
# for문
answer=[]
for d in data:
    answer.append(2*d)

In [10]:
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [11]:
#벡터화 연산: for문없이 한번에 처리 가능
x=np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
2*x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
# data *2 할 경우: data 2번 출력
data*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용된다. 

In [ ]:
a=np.array([1,2,3])
b=np.array([10,20,30])
2*a+