## 3.1 넘파이배열
많은 숫자 데이터를 하나의 변수에 넣고 관리 할 때 리스트는 속도가 느리고 메모리를 많이 차지하는 단점이 있다. 배열(array)을 사용하면 적은 메모리로 많은 데이터를 빠르게 처리할 수 있다.  
배열은 리스트와 비슷하지만 다음과 같은 점에서 다르다.   
1. 모든 원소가 같은 자료형이어야 한다. 
2. 원소의 갯수를 바꿀 수 없다.   
파이썬은 자체적으료 배열 자료형을 제공하지 않는다. 따라서 파이썬에서 배열을 사용하기 위한 표준 패키지인 넘파이를 임포트 해야한다.   

넘파이는 수치해석용 파이썬 패키지이다. 다차원의 배열자료구조 클래스인 ```ndarray```클래스를 지원하며 벡터와 행렬을 사용하는 선형대수 계산에 주로 사용된다.   

넘파이의 배열 연산은 C로 구현된 내부 반복문을 사용하기 때문에 파이썬 반복문에 비해 속도가 빠르며 벡터화 연산(vectorized operation)을 이용하여 간단한 코드로도 복잡한 선형 대수 연산을 수행할 수 있다. 또한 배열 인덱싱(array indexing)을 사용한 질의(Query) 기능을 이용하여 간단한 코드로도 복잡한 수식을 계산할 수 있다.


### 3.1.1 넘파이 패키지 임포트

In [1]:
import numpy as np

### 3.1.2 1차원 배열 만들기
넘파이의 ```array```함수에 리스트를 넣으면 ```ndarray```클래스 객체, 즉 배열로 변환해 준다. 

In [2]:
ar = np.array([0,1,2,3,4,5,6,7,8,9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(ar)

numpy.ndarray

만들어진 ndarray 객체의 표현식(representation)을 보면 바깥쪽에 array()란 것이 붙어 있을 뿐 리스트와 동일한 구조처럼 보인다. 그러나 배열 객체와 리스트 객체는 많은 차이가 있다.

우선 리스트 클래스 객체는 각각의 원소가 다른 자료형이 될 수 있다. 그러나 배열 객체 객체는 C언어의 배열처럼 연속적인 메모리 배치를 가지기 때문에 모든 원소가 같은 자료형이어야 한다. 이러한 제약사항이 있는 대신 원소에 대한 접근과 반복문 실행이 빨라진다

### 3.1.3 벡터화 연산
배열 객체는 배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리하는 벡터화 연산(vectorized operation)을 지원한다.

In [7]:
# 2배 만들기
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
# for문
answer=[]
for d in data:
    answer.append(2*d)

In [10]:
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [11]:
#벡터화 연산: for문없이 한번에 처리 가능
x=np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
2*x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
# data *2 할 경우: data 2번 출력
data*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용된다. 

In [15]:
a=np.array([1,2,3])
b=np.array([10,20,30])
2*a+b

array([12, 24, 36])

In [16]:
a==2

array([False,  True, False])

In [17]:
b>10

array([False,  True,  True])

In [18]:
(a==2)&(b>10)

array([False,  True, False])

### 3.1.4 2차원 배열 만들기

In [20]:
# 리스트의 리스트 이용
c=np.array([[0,1,2], [3,4,5]])
c  # 2 x 3 array

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
# 행의갯수
len(c)

2

In [24]:
#열의갯수
len(c[0])

3

#### 연습문제 3.1.1.1 
넘파이를 사용하여 다음과 같은 행렬을 만든다.
```
10 20 30 40
50 60 70 80
```

In [25]:
np.array([[10, 20, 30, 40], [50, 60, 70,80]])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 3.1.5 3차원 배열 만들기

In [26]:
#리스트의 리스트의 리스트
d = np.array([[[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]],
              [[11,12,13,14],
               [15,16,17,18],
               [19,20,21,22]]])

In [28]:
d # 2x3x4 array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [34]:
#3차원 배열의 길이
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

### 3.1.6 배열의 차원과 크기 알아내기
* ndim 속성: 차원 반환
* shape 속성: 배열 크기 반환

In [36]:
# a = np.arra([1,2,3])
a.ndim

1

In [37]:
a.shape

(3,)

In [38]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [39]:
c.ndim

2

In [40]:
c.shape

(2, 3)

In [41]:
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [42]:
d.ndim

3

In [43]:
d.shape

(2, 3, 4)

### 3.1.7 배열의 인덱싱

In [44]:
a=np.array([0,1,2,3,4])

In [45]:
a[2]

2

In [46]:
a[-1]

4

In [47]:
# 다차원배열은 콤마(comma,)사용햐여 접근. 

In [59]:
a=np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [60]:
a[0]

array([0, 1, 2])

In [61]:
a[0,0] # 첫번째 행의 첫번째 열

0

In [64]:
a[0,1]==a[0][1]
a[0,1] # 첫 번째 행의 두번째 열]

1

In [66]:
a[-1,-1] # 마지막 행의 마지막 열

5

### 3.1.8 배열 슬라이싱
다차원 배열의 원소 중 복수 개를 접근하려면 일반적인 파이썬슬라이싱과 컴마를 함께 사용하면 된다. 

In [69]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [82]:
# 첫번째 행의 열 전체
a[0, :] # = a[0]

array([0, 1, 2, 3])

In [84]:
# 두번째 행 두번째 열부터 끝열까지
a[1,1:]

array([5, 6, 7])

In [87]:
# 첫번째 행부터 두번째 행의 두번째열까지 
a[:2,:2]

array([[0, 1],
       [4, 5]])

#### 연습문제 3.1.1.2 
다음 행렬과 같은 행렬이 있다.
```
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
```
1. 이 행렬에서 값 7 을 인덱싱한다.
2. 이 행렬에서 값 14 을 인덱싱한다.
3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.


In [88]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [90]:
#1.이 행렬에서 값 7 을 인덱싱한다. 
m[1,2]

7

In [91]:
#2. 이 행렬에서 값 14 을 인덱싱한다.
m[-1,-1]

14

In [92]:
#3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[1,1:3]

array([6, 7])

In [93]:
#4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[1:,2]

array([ 7, 12])

In [94]:
#5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
m[:2,-2:]

array([[3, 4],
       [8, 9]])

### 3.1.9 팬시 인덱싱(fancy indexing) : 배열로 인덱싱해오기 
기존 인덱싱 방법인 숫자나 슬라이스로 인덱싱 정보를 받는 것 외에도, 위치정보를 나타내는 또다른 ```ndarray```배열을 받아 인덱싱 할 수 있다.  
1) Boolean인덱싱  
인덱스 배열의 원소가 True, False 두 값으로만 구성되며, 인덱스 배열의 크기가 원래 객체의 크기와 같아야 한다. 

In [98]:
# 짝수 값 원소만 골라내기 : 인덱스배열로 불러오기
a= np.array([0,1,2,3,4,5,6,7,8,9])
idx=np.array([True,False,True,False,True,False,True,False,True,False])
a[idx]

array([0, 2, 4, 6, 8])

In [99]:
# 짝수 값 원소만 골라내기 : 조건문으로 불러오기
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [100]:
a % 2 ==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [101]:
a[a%2==0]

array([0, 2, 4, 6, 8])

2) 정수 배열 인덱싱  

원래 객체의 원소의 위치를 나타내는 정수로 이루어진 배열. 원래 객체의 크기와 달라도 상관 없다. 

In [104]:
# 홀수번째 원소 골라내기
a= np.array([11,22,33,44,55,66,77,88,99])
idx=np.array([0,2,4,6,8])
a[idx]

array([11, 33, 55, 77, 99])

In [106]:
#반복출력
idx=([0,0,0,0,0,0,1,1,1,1,1,1,2,2,2,2,2,])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [107]:
#다차원배열
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [108]:
a[:,[True,False,True,False]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [110]:
a[[2,0,1],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

#### 연습문제 3.1.3

다음 행렬과 같은 배열이 있다.
```
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
```
1. 이 배열에서 3의 배수를 찾아라.
2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [111]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [112]:
# 1. 이 배열에서 3의 배수를 찾아라.
x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

In [113]:
#2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라
x[x%4==1]

array([ 1,  5,  9, 13, 17])

In [134]:
# 3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
x[(x%3==0)&(x%4==1)]

array([9])