## 3.2 배열의 생성과 변형
### 3.2.1 넘파이의 자료형
* 넘파이의 배열(ndarray 클래스)는 원소가 모두 같은 자료형 이어야 한다. 
* array명령으로 배열을 만들 때 자료형은 dtype인수를 활용 해 명시적으로 적용할 수 있다. 
* dtype인수가 없으면 주어진 데이터로 저장할 수 있는 자료형을 파이썬 스스로 유추한다. 

In [5]:
import numpy as np

In [6]:
x = np.array([1,2,3])
x.dtype

dtype('int32')

In [7]:
x = np.array([1.0,2.0,3])
x.dtype

dtype('float64')

In [8]:
import pandas as pd
tb=pd.read_html("https://datascienceschool.net/01%20python/03.02%20%EB%B0%B0%EC%97%B4%EC%9D%98%20%EC%83%9D%EC%84%B1%EA%B3%BC%20%EB%B3%80%ED%98%95.html")

In [14]:
tb[0]
# 시작하는문자열: 자료형,  숫자: 바이트 혹은 글자 수 . 생략 시 운영체제에 따라 알맞은 크기 할당

dtype 접두사        설명              사용 예
0         b       불리언       b (참 혹은 거짓)
1         i        정수         i8 (64비트)
2         u  부호 없는 정수         u8 (64비트)
3         f     부동소수점         f8 (64비트)
4         c  복소 부동소수점       c16 (128비트)
5         O        객체    0 (객체에 대한 포인터)
6         S   바이트 문자열       S24 (24 글자)
7         U  유니코드 문자열  U24 (24 유니코드 글자)

In [16]:
x = np.array([1,2,3], dtype='f')
x.dtype

dtype('float32')

In [17]:
x[0] + x[1]

3.0

In [20]:
x = np.array([1,2,3], dtype='U')  #U 대문자
x.dtype

dtype('<U1')

In [21]:
x[0] + x[1]

'12'

### 3.2.2 Inf와 NaN
* Inf: 무한대 (infinity) - np.inf  (ex: 1/0)
* NaN: 정의할 수 없는 숫자(Not a number) - np.nan (ex: log0)

In [22]:
np.array([0,1,-1,0])/np.array([1,0,0,0])

<ipython-input-22-dc768ac6b521>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1,-1,0])/np.array([1,0,0,0])
<ipython-input-22-dc768ac6b521>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1,-1,0])/np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

In [23]:
np.log(0)

<ipython-input-23-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [26]:
np.exp(-np.inf)

0.0

### 3.2.3 배열생성
* zeros, ones
* zeros_like, ones_like
* empty
* arange
* linspace, logspace

In [28]:
# zeros: 크기가 정해져 있고 모든 값이 0인 배열
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [32]:
# 크기로 튜플, 리스트 입력도 가능하다. 
b=np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
# dtype설정 가능
c = np.zeros((5,2), dtype="i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [34]:
# 문자열 배열시엔 모든 원소의 문자열 크기가 같아야 한다. 만약 더 큰 크기의 문자열을 할당하면 잘릴 수 있다.
d=np.zeros(5, dtype='U4')
d

array(['', '', '', '', ''], dtype='<U4')

In [36]:
d[0]="abc"
d[1]="abcd"
d[2]="ABCDE"   #4글자까지만 할당했기 때문에 'E'는 잘린다. 
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [38]:
# ones: 1로 이루어진 배열
e=np.ones((2,3,4), dtype='i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [40]:
#ones_like, zeros_like: 크기 지정을, 튜플이 아닌 이미 존재하는 다른 배열과 같이 만들고 싶을 때
f=np.ones_like(b, dtype='f')
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [45]:
# empty: 특정한 지정값 설정 없이, 배열을 만들 고 싶을 때 
g = np.empty((4, 3))
g

array([[1.13404596e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 2.35825919e+184],
       [6.52746528e-038, 2.94940857e+179, 6.95911308e-042],
       [5.49171309e+174, 9.60290966e-071, 3.79744065e+175]])

In [48]:
# arange: 특정한 규칙에 따라 증가하는 수열 생성 (range와 유사)
np.arange(10) # 0 .. n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(3,21,2)  # 시작, 끝(포함하지 않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [52]:
# linspace, logspace: 선형구간, 로그 구간을  지정한 구간의 수 만큼 분할 한다. 
np.linspace(0,100,5) # 시작, 끝, 갯수

array([  0.,  25.,  50.,  75., 100.])

In [53]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

### 3.2.3 전치연산